mutation CREATE_COMMENT {
  createComment(comment: { content: "abc", postid: 351 }) {
    content
    date
    id
    employeeid
    employee {
      name
      email
      password
      createdat
      isactive
      id
      description
      slug
    }
  }
}

query SINGLE_COMMENT {
  comment(id: 672) {
    content
    date
    id
    employeeid
    employee {
      name
      email
      password
      createdat
      isactive
      id
      description
      slug
    }
  }
}

query POST_COMMENTS_ASC {
  postComments(options: { id: 351, page: 1, order: "asc" }) {
    content
    date
    postid
    id
    employeeid
    employee {
      name
      email
      password
      createdat
      isactive
      id
      description
      slug
    }
  }
}

query POST_COMMENTS_DESC {
  postComments(options: { id: 351, page: 1, order: "desc" }) {
    content
    date
    postid
    id
    employeeid
    employee {
      name
      email
      password
      createdat
      isactive
      id
      description
      slug
    }
  }
}
query COMMENT_REPLIES {
  commentReplies(options: { id: 140, page: 3, order: "desc" }) {
    content
    date
    commentid
    postid
    id
    employeeid
    employee {
      name
      email
      password
      createdat
      isactive
      id
      description
      slug
    }
  }
}
