query LIST_ALL_POSTS_DESC {
  posts(options: { page: 1, order: "DESC" }) {
    content
    id
    content
    date
    employee {
      id
      name
      department
      description
      slug
    }
  }
}

query LIST_ALL_POSTS_ASC {
  posts(options: { page: 1, order: "ASC" }) {
    content
    id
    content
    date
    employee {
      id
      name
      department
      description
      slug
    }
  }
}

query LIST_POST_BY_DEPARTMENT_ASC {
  posts(options: { page: 1, department: "hr", order: "ASC" }) {
    content
    id
    content
    date
    employee {
      department
    }
  }
}
query LIST_POST_BY_DEPARTMENT_DESC {
  posts(options: { page: 1, department: "hr", order: "DESC" }) {
    content
    id
    content
    date
    employee {
      department
    }
  }
}

query LIST_POST_BY_USER {
  posts(options: { page: 1, userId: 5, order: "DESC" }) {
    content
    id
    content
    date
    employee {
      name
      department
    }
  }
}

query SINGLE_POST {
  post(id: 353) {
    content
    id
    content
    date
    employee {
      id
      name
      department
      description
      slug
      email
    }
  }
}
