query SHOW_POST_REACTIONS {
  showPostReactions(id: 352) {
    count
    emoji
  }
}

query SHOW_COMMENT_REACTIONS {
  showCommentReactions(id: 24) {
    count
    emoji
  }
}

query SHOW_POST_REACTED_USERS {
  showPostReactedUsers(id: 352) {
    id
    employee {
      name
      email
    }
    type {
      id
      name
      emoji
    }
  }
}

query SHOW_COMMENT_REACTED_USERS {
  showCommentReactedUsers(id: 24, reactionId: 1) {
    id
    employee {
      name
      email
    }
    type {
      id
      name
      emoji
    }
  }
}

mutation GIVE_POST_REACTION {
  givePostReaction(reaction: { reactionid: 1, postid: 352 }) {
    success
    text
  }
}

mutation GIVE_COMMENT_REACTION {
  giveCommentReaction(reaction: { reactionid: 1, commentid: 140 }) {
    success
    text
  }
}
