mutation SIGN_IN {
  signIn(email: "akif@mail.com", password: "124") {
    name
    email
    password
    createdat
    isactive
    id
    token
    description
    slug
  }
}

query USER_PROFILE {
  profile(slug: "sebnem-ferah") {
    name
    description
    slug
    id
    email
  }
}
